workflows:
  ios-workflow:
    name: iOS build
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Ensure iOS project exists
        script: |
          flutter create --platforms=ios .
      - name: Build iOS
        script: |
          flutter build ios --no-codesign
      - name: Run on iOS Simulator
        script: |
          flutter drive --target=integration_test/app_test.dart --device "iOS Simulator"
